/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TransparentCharity } from "./TransparentCharity";
export * as factories from "./factories";
export { TransparentCharity__factory } from "./factories/TransparentCharity__factory";
