/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace TransparentCharity {
  export type DonationStruct = {
    donor: AddressLike;
    amount: BigNumberish;
    timestamp: BigNumberish;
  };

  export type DonationStructOutput = [
    donor: string,
    amount: bigint,
    timestamp: bigint
  ] & { donor: string; amount: bigint; timestamp: bigint };
}

export interface TransparentCharityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "campaignCount"
      | "campaigns"
      | "createCampaign"
      | "donate"
      | "getCampaign"
      | "getDonations"
      | "uploadProof"
      | "withdrawFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CampaignCreated"
      | "DonationReceived"
      | "FundsWithdrawn"
      | "ProofUploaded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "campaignCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "donate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDonations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "uploadProof",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "campaignCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDonations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uploadProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    name: string,
    targetAmount: BigNumberish,
    owner: AddressLike
  ];
  export type OutputTuple = [
    id: bigint,
    name: string,
    targetAmount: bigint,
    owner: string
  ];
  export interface OutputObject {
    id: bigint;
    name: string;
    targetAmount: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DonationReceivedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    donor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [campaignId: bigint, donor: string, amount: bigint];
  export interface OutputObject {
    campaignId: bigint;
    donor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsWithdrawnEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    amount: BigNumberish,
    owner: AddressLike
  ];
  export type OutputTuple = [campaignId: bigint, amount: bigint, owner: string];
  export interface OutputObject {
    campaignId: bigint;
    amount: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofUploadedEvent {
  export type InputTuple = [campaignId: BigNumberish, proofHash: string];
  export type OutputTuple = [campaignId: bigint, proofHash: string];
  export interface OutputObject {
    campaignId: bigint;
    proofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TransparentCharity extends BaseContract {
  connect(runner?: ContractRunner | null): TransparentCharity;
  waitForDeployment(): Promise<this>;

  interface: TransparentCharityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  campaignCount: TypedContractMethod<[], [bigint], "view">;

  campaigns: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean, string] & {
        id: bigint;
        name: string;
        description: string;
        owner: string;
        targetAmount: bigint;
        amountRaised: bigint;
        withdrawn: boolean;
        proofHash: string;
      }
    ],
    "view"
  >;

  createCampaign: TypedContractMethod<
    [_name: string, _description: string, _targetAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  donate: TypedContractMethod<[_campaignId: BigNumberish], [void], "payable">;

  getCampaign: TypedContractMethod<
    [_campaignId: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean, string] & {
        id: bigint;
        name: string;
        description: string;
        owner: string;
        targetAmount: bigint;
        amountRaised: bigint;
        withdrawn: boolean;
        proofHash: string;
      }
    ],
    "view"
  >;

  getDonations: TypedContractMethod<
    [_campaignId: BigNumberish],
    [TransparentCharity.DonationStructOutput[]],
    "view"
  >;

  uploadProof: TypedContractMethod<
    [_campaignId: BigNumberish, _proofHash: string],
    [void],
    "nonpayable"
  >;

  withdrawFunds: TypedContractMethod<
    [_campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "campaignCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean, string] & {
        id: bigint;
        name: string;
        description: string;
        owner: string;
        targetAmount: bigint;
        amountRaised: bigint;
        withdrawn: boolean;
        proofHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [_name: string, _description: string, _targetAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "donate"
  ): TypedContractMethod<[_campaignId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getCampaign"
  ): TypedContractMethod<
    [_campaignId: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean, string] & {
        id: bigint;
        name: string;
        description: string;
        owner: string;
        targetAmount: bigint;
        amountRaised: bigint;
        withdrawn: boolean;
        proofHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDonations"
  ): TypedContractMethod<
    [_campaignId: BigNumberish],
    [TransparentCharity.DonationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "uploadProof"
  ): TypedContractMethod<
    [_campaignId: BigNumberish, _proofHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<[_campaignId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DonationReceived"
  ): TypedContractEvent<
    DonationReceivedEvent.InputTuple,
    DonationReceivedEvent.OutputTuple,
    DonationReceivedEvent.OutputObject
  >;
  getEvent(
    key: "FundsWithdrawn"
  ): TypedContractEvent<
    FundsWithdrawnEvent.InputTuple,
    FundsWithdrawnEvent.OutputTuple,
    FundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ProofUploaded"
  ): TypedContractEvent<
    ProofUploadedEvent.InputTuple,
    ProofUploadedEvent.OutputTuple,
    ProofUploadedEvent.OutputObject
  >;

  filters: {
    "CampaignCreated(uint256,string,uint256,address)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "DonationReceived(uint256,address,uint256)": TypedContractEvent<
      DonationReceivedEvent.InputTuple,
      DonationReceivedEvent.OutputTuple,
      DonationReceivedEvent.OutputObject
    >;
    DonationReceived: TypedContractEvent<
      DonationReceivedEvent.InputTuple,
      DonationReceivedEvent.OutputTuple,
      DonationReceivedEvent.OutputObject
    >;

    "FundsWithdrawn(uint256,uint256,address)": TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;
    FundsWithdrawn: TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;

    "ProofUploaded(uint256,string)": TypedContractEvent<
      ProofUploadedEvent.InputTuple,
      ProofUploadedEvent.OutputTuple,
      ProofUploadedEvent.OutputObject
    >;
    ProofUploaded: TypedContractEvent<
      ProofUploadedEvent.InputTuple,
      ProofUploadedEvent.OutputTuple,
      ProofUploadedEvent.OutputObject
    >;
  };
}
